# Generated by Django 2.2.6 on 2019-10-27 16:50

from django.db import migrations
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icongrid',
            name='icon',
            field=fontawesome.fields.IconField(blank=True, max_length=60),
        ),
    ]
