# Generated by Django 2.2.6 on 2019-10-27 17:10

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landingapp', '0002_icongrid_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icongrid',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
    ]
