# Generated by Django 2.2.6 on 2019-10-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingapp', '0004_imageshowcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageshowcase',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
