# Generated by Django 2.2.6 on 2019-10-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingapp', '0005_imageshowcase_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField()),
            ],
        ),
    ]
